apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devops-handson-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: devops-handson
    spec:
      containers:
      - name: myapp
        image: gcr.io/FIXME/devops-handson:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-handson
spec:
  type: NodePort
  selector:
    app: devops-handson
  ports:
  - name: myapp
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devops-handson-ingress
spec:
  backend:
    serviceName: devops-handson
    servicePort: 8080
